INSERT INTO wk_vendas.cidades (uf, nome) VALUES
(1,	'Rio Branco'),
(2,	'Maceió'),
(3,	'Manaus'),
(4,	'Macapá'),
(5,	'Salvador'),
(6,	'Fortaleza'),
(7,	'Brasília'),
(8,	'Vitória'),
(9,	'Goiânia'),
(10, 'São Luís'),
(11, 'Belo Horizonte'),
(12, 'Campo Grande'),
(13, 'Cuiabá'),
(14, 'Belém'),
(15, 'João Pessoa'),
(16, 'Recife'),
(17, 'Teresina'),
(18, 'Curitiba'),
(19, 'Rio de Janeiro'),
(20, 'Natal'),
(21, 'Porto Velho'),
(22, 'Boa Vista'),
(23, 'Porto Alegre'),
(24, 'Florianópolis'),
(25, 'Aracaju'),
(26, 'São Paulo'),
(27, 'Palmas');